-- 실습과제 4
SELECT NAME FROM CUSTOMERS ORDER BY NAME ASC;
SELECT ACCOUNT_ID, BALANCE FROM ACCOUNTS ORDER BY BALANCE DESC;
SELECT TRANSACTION_ID, AMOUNT FROM TRANSACTIONS ORDER BY AMOUNT ASC;
SELECT LOAN_ID, CUSTOMER_ID FROM LOANS ORDER BY AMOUNT DESC;

-- 실습과제 5
SELECT NAME, EMAIL FROM CUSTOMERS ORDER BY NAME ASC, EMAIL DESC;
SELECT * FROM ACCOUNTS ORDER BY BALANCE DESC, ACCOUNT_ID ASC;
SELECT * FROM TRANSACTIONS ORDER BY TRANSACTION_TYPE ASC, AMOUNT DESC;
SELECT * FROM LOANS ORDER BY STATUS ASC, AMOUNT DESC;

-- 실습과제 6
SELECT 
    STATUS,
    SUM(AMOUNT) AS TOTAL_AMOUNT, 
    COUNT(*) AS TOTAL_COUNT
FROM LOANS WHERE STATUS = 'APPROVED' GROUP BY STATUS;

SELECT TO_CHAR(TRANSACTION_DATE, 'YYYY-MM') AS MONTH, SUM(AMOUNT) AS MONTHLY_AMOUNT
FROM TRANSACTIONS
GROUP BY TO_CHAR(TRANSACTION_DATE, 'YYYY-MM')
HAVING SUM(AMOUNT) >= 10000;

SELECT 
    BRANCH_ID,
    AVG(AMOUNT) AS AVG_AMOUNT,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM LOANS
WHERE STATUS = 'APPROVED'
GROUP BY BRANCH_ID;