-- 실습 8번
-- 1
SELECT
    C.NAME
FROM CUSTOMERS C
WHERE CUSTOMER_ID IN (
    SELECT
        L.CUSTOMER_ID
    FROM LOANS L
    WHERE BRANCH_ID IN (
        SELECT
            BRANCH_ID
        FROM BRANCHES B
        WHERE B.LOCATION = 'Location 1'
    )
);

-- 2
SELECT
    *
FROM TRANSACTIONS T
WHERE T.ACCOUNT_ID IN (
    SELECT A.ACCOUNT_ID
    FROM ACCOUNTS A
    WHERE A.CUSTOMER_ID = 100
);

-- 3
SELECT
    *
FROM ACCOUNTS A1
WHERE A1.BALANCE = (
    SELECT
        MAX(A2.BALANCE)
    FROM ACCOUNTS A2
    WHERE A1.CUSTOMER_ID = A2.CUSTOMER_ID
);

-- 실습 9번
-- 1
SELECT CUSTOMER_ID FROM CUSTOMERS
MINUS
SELECT CUSTOMER_ID FROM LOANS;

-- 2
SELECT ACCOUNT_ID FROM TRANSACTIONS
INTERSECT
SELECT ACCOUNT_ID FROM ACCOUNTS;

-- 3
SELECT BRANCH_ID FROM BRANCHES
MINUS
SELECT BRANCH_ID FROM LOANS;