-- 1
SELECT *
FROM (
    SELECT DISTINCT
        B.NAME,
        SUM(NVL(L.AMOUNT, 0)) OVER (PARTITION BY B.BRANCH_ID) AS BRANCH_SUM,
        ROUND(AVG(NVL(L.AMOUNT, 0)) OVER (), 2) AS TOTAL_AVG
    FROM BRANCHES B, LOANS L
    WHERE B.BRANCH_ID = L.BRANCH_ID AND L.STATUS = 'APPROVED'
) T
WHERE T.BRANCH_SUM < T.TOTAL_AVG;

-- 2
SELECT
    E1.EMPLOYEE_ID,
    E1.NAME,
    NVL(E2.NAME, 'NO MANAGER'),
    NVL(D.DEPARTMENT_NAME, 'NO DEPARTMENT')
FROM EMPLOYEES E1
LEFT OUTER JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
LEFT OUTER JOIN DEPARTMENTS D
ON E2.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT 
    T.EMPLOYEE_ID,
    T.NAME,
    NVL(T.MANAGER_NAME, 'NO MANAGER'),
    NVL((SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = T.MANAGER_DEPARTMENT_ID), 'NO DEPARTMENT')
FROM (
    SELECT 
        EMPLOYEE_ID,
        NAME,
        PRIOR NAME AS MANAGER_NAME,
        PRIOR DEPARTMENT_ID AS MANAGER_DEPARTMENT_ID
    FROM EMPLOYEES
    START WITH MANAGER_ID IS NULL
    CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
) T
ORDER BY EMPLOYEE_ID;

-- 3
SELECT 
    EMPLOYEE_ID,
    NAME,
    SALARY,
    ROUND(SALARY * 100 / SUM(SALARY) OVER (), 2) AS RATE
FROM EMPLOYEES
WHERE SALARY IS NOT NULL
ORDER BY RATE DESC;

-- 4
SELECT
    ACCOUNT_ID,
    MAX_AMOUNT
FROM (
    SELECT
        ACCOUNT_ID,
        MAX(AMOUNT) AS MAX_AMOUNT,
        DENSE_RANK() OVER (ORDER BY MAX(AMOUNT) DESC) AS DR
    FROM TRANSACTIONS T
    GROUP BY ACCOUNT_ID
)
WHERE DR <= 5;

-- 5
SELECT
    DEPARTMENT_ID,
    MAX(SALARY) - MIN(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

-- 6
SELECT
    EMPLOYEE_ID,
    NAME,
    SALARY,
    ROUND(AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID)) AS DEPT_AVG_SALARY,
    ROUND(SALARY - AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID)) AS DIFF_SALARY
FROM EMPLOYEES
WHERE SALARY IS NOT NULL;

-- 7
SELECT *
FROM (
    SELECT 
        LTRIM(SYS_CONNECT_BY_PATH(NAME, ' > '), ' > ')
    FROM EMPLOYEES
    START WITH EMPLOYEE_ID = 241
    CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID
    ORDER BY LEVEL DESC
)
WHERE ROWNUM = 1;

SELECT 
    MAX(LTRIM(SYS_CONNECT_BY_PATH(NAME, ' > '), ' > '))
FROM EMPLOYEES
START WITH NAME = 'Employee 241'
CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID;

-- 8
SELECT *
FROM (
    SELECT
        *
    FROM EMPLOYEES
    WHERE SALARY IS NOT NULL
    ORDER BY SALARY DESC, NAME
)
WHERE ROWNUM <= 10;

-- 9 
SELECT
    NVL(TO_CHAR(HIRE_DATE, 'YYYY'), 'ALL YEARS'),
    SUM(SALARY)
FROM EMPLOYEES
GROUP BY ROLLUP(TO_CHAR(HIRE_DATE, 'YYYY'))
ORDER BY TO_CHAR(HIRE_DATE, 'YYYY');

-- 10
SELECT
    D.DEPARTMENT_NAME,
    E.JOB_ID,
    SUM(E.SALARY)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY GROUPING SETS(D.DEPARTMENT_NAME, E.JOB_ID, ())
ORDER BY D.DEPARTMENT_NAME, E.JOB_ID;

-- 11
SELECT
    DEPARTMENT_ID,
    NAME,
    SALARY,
    SUM(SALARY) OVER (PARTITION BY DEPARTMENT_ID 
        ORDER BY SALARY RANGE BETWEEN 100 PRECEDING AND 100 FOLLOWING) AS SUM_SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
    AND SALARY IS NOT NULL;
    
-- 12
SELECT
    EMPLOYEE_ID,
    SALARY,
    CASE
        WHEN SALARY > AVG(SALARY) OVER (PARTITION BY JOB_ID) THEN '직무 평균 이상'
        ELSE '직무 평균 이하'
    END AS JOB_AVG,
    CASE
        WHEN SALARY > AVG(SALARY) OVER () THEN '전체 평균 이상'
        ELSE '전체 평균 이하'
    END AS TOT_AVG
FROM EMPLOYEES
WHERE SALARY IS NOT NULL
ORDER BY EMPLOYEE_ID;
