-- 1. 직원의 직무 변경 기록과 상태
SELECT
    E.NAME,
    NVL(J.JOB_ID, 'No Change')
FROM EMPLOYEES E
LEFT OUTER JOIN JOB_HISTORY J
    ON E.EMPLOYEE_ID = J.EMPLOYEE_ID;
    
-- 2. 특정 패턴의 직원과 부서 정보 조회
SELECT
    E.NAME,
    D.DEPARTMENT_NAME,
    NVL(SALARY, 0)
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.NAME LIKE '%Employee 1%'
ORDER BY D.DEPARTMENT_NAME;

SELECT
    E.NAME,
    D.DEPARTMENT_NAME,
    NVL(SALARY, 0)
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.NAME LIKE '%Employee 1%'
ORDER BY TO_NUMBER(REGEXP_SUBSTR(D.DEPARTMENT_NAME, '[0-9]+$'));

-- 3. 최근 6개월 거래 내역 조회
SELECT
    A.ACCOUNT_ID,
    T.AMOUNT,
    TO_CHAR(T.TRANSACTION_DATE, 'YYYY-MM-DD HH:MI:SS') AS TRANSACTION_DATE,
    C.CUSTOMER_ID,
    C.NAME
FROM TRANSACTIONS T, ACCOUNTS A, CUSTOMERS C
WHERE T.ACCOUNT_ID = A.ACCOUNT_ID 
    AND A.CUSTOMER_ID = C.CUSTOMER_ID
    AND T.TRANSACTION_DATE >= ADD_MONTHS(SYSDATE, -6);
    
-- 4. 특정 부서의 직무별 직원수
SELECT
    E.JOB_ID,
    COUNT(*)
FROM DEPARTMENTS D, EMPLOYEES E
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND (
        D.DEPARTMENT_NAME = 'Department 3'
        OR D.DEPARTMENT_NAME = 'Department 4'
        OR D.DEPARTMENT_NAME = 'Department 5'
        OR D.DEPARTMENT_NAME = 'Department 6'
    )
GROUP BY E.JOB_ID;

-- 5. 계좌 유형별 평균 잔액
SELECT
    ACCOUNT_TYPE,
    TRUNC(AVG(BALANCE), 2)
FROM ACCOUNTS
GROUP BY ACCOUNT_TYPE
ORDER BY AVG(BALANCE) DESC;

-- 6. 각 계좌별 거래 횟수
SELECT
    *
FROM (
    SELECT
        A.ACCOUNT_ID,
        COUNT(T.TRANSACTION_ID) AS NUMS
    FROM ACCOUNTS A
    LEFT OUTER JOIN TRANSACTIONS T
    ON A.ACCOUNT_ID = T.ACCOUNT_ID
    GROUP BY A.ACCOUNT_ID
)
ORDER BY NUMS;

-- 7. 특정 기간의 고객별 총 거래 내역
SELECT 
    *
FROM (
    SELECT
        C.CUSTOMER_ID,
        SUM(T.AMOUNT) AS TOTAL_AMOUNT
    FROM CUSTOMERS C
    LEFT OUTER JOIN ACCOUNTS A
        ON C.CUSTOMER_ID = A.CUSTOMER_ID
    LEFT OUTER JOIN TRANSACTIONS T
        ON A.ACCOUNT_ID = T.ACCOUNT_ID
    WHERE TRUNC(T.TRANSACTION_DATE, 'DD')
        BETWEEN TO_DATE('2024-01-01', 'YYYY-MM-DD') AND TO_DATE('2025-12-31', 'YYYY-MM-DD')
    GROUP BY C.CUSTOMER_ID
    ORDER BY TOTAL_AMOUNT DESC NULLS LAST
)
WHERE ROWNUM <= 10;

-- 8. 급여가 NULL인 직원
SELECT
    E.NAME,
    D.DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
WHERE SALARY IS NULL;

-- 9. 고객별 가장 높은 대출 금액 조회
SELECT
    *
FROM (
    SELECT
        C.CUSTOMER_ID,
        MAX(L.AMOUNT) AS MAX_AMOUNT
    FROM CUSTOMERS C, LOANS L
    WHERE C.CUSTOMER_ID = L.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID
    ORDER BY MAX_AMOUNT DESC
)
WHERE ROWNUM <= 15;

-- 10. 특정 급여 구간과 부서별 직원 분포
SELECT
    D.DEPARTMENT_ID,
    COUNT(*) AS NUM
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.SALARY BETWEEN 7000 AND 15000
GROUP BY D.DEPARTMENT_ID
HAVING COUNT(*) >= 5
ORDER BY NUM DESC;