-- 실습과제 11
-- 1
SELECT CATEGORY_ID, CATEGORY_NAME, LEVEL
FROM SHOPPING_CATEGORIES
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID
ORDER SIBLINGS BY CATEGORY_NAME;

-- 2
SELECT CATEGORY_ID, CATEGORY_NAME, LTRIM(SYS_CONNECT_BY_PATH(CATEGORY_NAME, ' > '), ' > ')
FROM SHOPPING_CATEGORIES
WHERE CATEGORY_NAME LIKE '%Phones%'
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;

SELECT CATEGORY_ID, CATEGORY_NAME, LTRIM(SYS_CONNECT_BY_PATH(CATEGORY_NAME, ' > '), ' > ')
FROM SHOPPING_CATEGORIES
START WITH CATEGORY_NAME LIKE '%Phones%'
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;

-- 3
SELECT MAX(LEVEL)
FROM SHOPPING_CATEGORIES
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;

-- 실습과제 12
-- 1
SELECT 
    DEPARTMENT_ID,
    SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY ROLLUP(DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

-- 2
SELECT 
    HIRE_DATE,
    COUNT(*)
FROM EMPLOYEES
GROUP BY ROLLUP(HIRE_DATE)
HAVING COUNT(*) >= 2;

-- 3
SELECT
    NVL(B.NAME, 'All Branch'),
    NVL(SUM(L.AMOUNT), 0)
FROM BRANCHES B
LEFT OUTER JOIN LOANS L
ON B.BRANCH_ID = L.BRANCH_ID
GROUP BY ROLLUP(B.NAME)
ORDER BY B.NAME;