SELECT
    B.NAME AS BRANCH_NAME,
    C.NAME AS CUSTOMER_NAME,
    L.AMOUNT AS AMOUNT
FROM BRANCHES B
LEFT OUTER JOIN LOANS L
    ON B.BRANCH_ID = L.BRANCH_ID
LEFT OUTER JOIN CUSTOMERS C
    ON L.CUSTOMER_ID = C.CUSTOMER_ID;

--SELECT 
--    B.NAME AS BRANCH_NAME,
--    C.NAME AS CUSTOMER_NAME,
--    COUNT(L.AMOUNT) AS COUNT,
--    SUM(L.AMOUNT) AS AMOUNT
--FROM BRANCHES B
--LEFT OUTER JOIN LOANS L
--    ON B.BRANCH_ID = L.BRANCH_ID
--LEFT OUTER JOIN CUSTOMERS C
--    ON L.CUSTOMER_ID = C.CUSTOMER_ID
--GROUP BY B.NAME, C.NAME
--ORDER BY B.NAME, C.NAME;

SELECT
    C.NAME AS NAME,
    C.EMAIL AS EMAIL
FROM CUSTOMERS C, ACCOUNTS A
WHERE C.CUSTOMER_ID = A.CUSTOMER_ID
    AND BALANCE >= 50000;
    
SELECT 
    C.NAME,
    L.AMOUNT
FROM LOANS L, CUSTOMERS C
WHERE L.CUSTOMER_ID = C.CUSTOMER_ID
    AND L.STATUS = 'PENDING';
    
