-- 실습과제 10
-- 1
SELECT 
    TRANSACTION_ID,
    ACCOUNT_ID,
    AMOUNT,
    SUM(AMOUNT) OVER (PARTITION BY ACCOUNT_ID ORDER BY TRANSACTION_DATE ROWS UNBOUNDED PRECEDING) AS TOTAL_SUM
FROM TRANSACTIONS;

-- 2
SELECT 
    TRANSACTION_ID,
    ACCOUNT_ID,
    AMOUNT,
    MAX(ABS(AMOUNT)) OVER (PARTITION BY ACCOUNT_ID) AS MAX_AMOUNT,
    ROUND(ABS(AMOUNT) / MAX(ABS(AMOUNT)) OVER (PARTITION BY ACCOUNT_ID), 2) AS RATE
FROM TRANSACTIONS;

-- 3
SELECT
    LOAN_ID,
    BRANCH_ID,
    AMOUNT,
    SUM(AMOUNT) OVER (PARTITION BY BRANCH_ID ORDER BY LOAN_DATE ROWS UNBOUNDED PRECEDING) AS CUM_AMOUNT
FROM LOANS;

-- 4
SELECT
    ACCOUNT_ID,
    CUSTOMER_ID,
    BALANCE,
    ROUND(AVG(BALANCE) OVER (PARTITION BY CUSTOMER_ID), 2) AS AVG_BALANCE
FROM ACCOUNTS;